// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ProjetoWTools;

{ITE} {DFMFileType} {wConfig.dfm}
{ITE} {DFMFileType} {wListaProjetos.dfm}
{ITE} {DFMFileType} {wListaProjetosDeTestes.dfm}
{ITE} {DFMFileType} {wPrincipal.dfm}
{ITE} {RCFileType} {Win32\Debug\ProjetoWTools_DRC.rc}

{$R 'wConfig.dfm' 'FConfig:TForm'}
{$R 'wListaProjetos.dfm' 'FListaProjetos:TForm'}
{$R 'wListaProjetosDeTestes.dfm' 'FListaProjetosTestes:TForm'}
{$R 'wPrincipal.dfm' 'FPrincipal:TForm'}
{$R 'Win32\Debug\ProjetoWTools_DRC.res' 'Win32\Debug\ProjetoWTools_DRC.rc'}

{$E ENU}

begin
end.
